language: go

matrix:
  include:
    - go: "1.11.x"
      install:
        - go mod download
      script:
        - GO111MODULE=on go test -race -v -coverprofile=coverage.txt -covermode=atomic -mod=vendor ./...
      env:
        - GO111MODULE=on

script:
  - if [ -n "$(go fmt ./...)" ]; then exit 1; fi
  - go build

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only: [master]
