language: go

matrix:
  include:
    - go: "1.10.x"
      script:
        - go test -race -v -coverprofile=coverage.txt -covermode=atomic ./...
      install:
        - go get -u -v $(go list -f '{{join .Imports "\n"}}{{"\n"}}{{join .TestImports "\n"}}' ./... | sort | uniq | grep -v filme)
    - go: "1.11.x"
      install:
        - go mod download
      script:
        - go test -race -v -coverprofile=coverage.txt -covermode=atomic -mod=vendor ./...
      env:
        - GO111MODULE=on

script:
  - if [ -n "$(go fmt ./...)" ]; then exit 1; fi
  - go build

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only: [master]
