language: go

notifications:
  email: false

# Only clone the most recent commit
git:
  depth: 1

matrix:
  include:
    - go: "1.11.x"
    - go: tip

env:
  - GO111MODULE=on

install:
  - go mod download

script:
  - if [ -n "$(go fmt ./...)" ]; then exit 1; fi
  - go test -race -v -coverprofile=coverage.txt -covermode=atomic ./...
  - go build

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only: [master]
