language: go

matrix:
  include:
    - go: "1.10.x"
      script:
        - go test -race -v -coverprofile=coverage.txt -covermode=atomic ./...
      install:
        - go get -u -v $(go list -f '{{join .Imports "\n"}}{{"\n"}}{{join .TestImports "\n"}}' ./... | sort | uniq | grep -v filme)
    - go: "1.11.x"
      install:
        - go get .
      script:
        - go test -race -v -coverprofile=coverage.txt -covermode=atomic -mod=vendor ./...
      env:
        - GO111MODULE=on

script:
  - OUT="$(gofmt -l -d ./)"; test -z "$OUT" || (echo "$OUT" && return 1)
  - OUT="$(golint ./...)"; test -z "$OUT" || (echo "$OUT" && return 1)
  - go vet -v ./...
  - go build

after_success:
  - bash <(curl -s https://codecov.io/bash)
