language: go

go:
  - 1.11.x

notifications:
  email: false

git:
  depth: 1

env:
  - GO111MODULE=on

script:
  - if [ -n "$(go fmt ./...)" ]; then exit 1; fi
  - go test -race -v -coverprofile=coverage.txt -covermode=atomic ./...
  - go build

after_success:
  - bash <(curl -s https://codecov.io/bash)

#branches:
#  only: [master]
