// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: torrents.proto

package proto

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"

	context "context"

	api "github.com/asim/go-micro/v3/api"

	client "github.com/asim/go-micro/v3/client"

	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Torrents service

func NewTorrentsEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Torrents service

type TorrentsService interface {
	Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
}

type torrentsService struct {
	c    client.Client
	name string
}

func NewTorrentsService(name string, c client.Client) TorrentsService {
	return &torrentsService{
		c:    c,
		name: name,
	}
}

func (c *torrentsService) Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.name, "Torrents.Search", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Torrents service

type TorrentsHandler interface {
	Search(context.Context, *SearchRequest, *SearchResponse) error
}

func RegisterTorrentsHandler(s server.Server, hdlr TorrentsHandler, opts ...server.HandlerOption) error {
	type torrents interface {
		Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error
	}
	type Torrents struct {
		torrents
	}
	h := &torrentsHandler{hdlr}
	return s.Handle(s.NewHandler(&Torrents{h}, opts...))
}

type torrentsHandler struct {
	TorrentsHandler
}

func (h *torrentsHandler) Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.TorrentsHandler.Search(ctx, in, out)
}
