openapi: 3.0.2
info:
  version: '0.1'
  title: 'filme api'
  description: 'an API for filme'
  contact:
    email: 'florinutz@gmail.com'
servers:
  - description: 'SwaggerHub API Auto Mocking'
    url: https://virtserver.swaggerhub.com/phlo/filme/1
paths:
  /:
    get:
      summary: 'lists films'
      parameters:
        - $ref: '#/components/parameters/category'
        - $ref: '#/components/parameters/encoding'
        - $ref: '#/components/parameters/order'
        - $ref: '#/components/parameters/sort'
        - name: filters
          in: query
          content:
            application/json:
              schema:
                type: object
                properties:
                  leechers-min:
                    type: integer
                  leechers-max:
                    type: integer
                  page-min:
                    type: integer
                  page-max:
                    type: integer
                  seeders-min:
                    type: integer
                  seeders-max:
                    type: integer
                  size:
                    type: integer
      responses:
        '200':
          $ref: '#/components/responses/ListOk'
        default:
          $ref: '#/components/responses/ErrorGeneric'

components:
  parameters:
    sort:
      name: sort
      in: query
      schema:
        type: string
        enum: [time, size, seeders, leechers]
      required: false
      description: >
        Sort order:
         * `asc` - Ascending from A to Z
         * `desc` - Descending from Z to A
    order:
      name: order
      in: query
      schema:
        type: string
        enum: [asc, desc]
      required: false
      description: 'order'
    category:
      name: category
      in: query
      schema:
        type: string
        enum: [all, tv, documentaries, anime, xxx, movies]
        default: all
      required: false
      description: 'Specifies the film category'
    encoding:
      name: encoding
      in: query
      schema:
        type: string
        enum: [h264-x264, hd, uhd, hevc-x265, mp4, svcd-vcd, divx-xvid, dvd]
      required: false
      description: 'Specifies the film encoding'
  schemas:
    item:
      type: object
      properties:
        title:
          type: string
        url:
          type: string
    error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
  responses:
    ListOk:
      description: 'json list of items'
      content:
        application/json:
          schema:
            type: object
            additionalProperties:
              $ref: '#/components/schemas/item'
    ErrorGeneric:
      description: An error occurred.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'